SELECT 
	
    MENT.MENT_ID,
	MENT.MENT_ETIQUETA "title",
	MENT.MENT_SECCION,
    MEND_ENLACE "path",
    MEND_PADRE,
    MEND_ID,
    MEND_NOMBRE,
    MENT_IMAGEN
FROM 
	SAB.SAB_GENE_MENT MENT,SAB.SAB_GENE_MEND MEND, SAB.SAB_GENE_SEGU SEGU ,SAB.SAB_GENE_ROLU RU
    
    WHERE RU.ROLU_USUARIO_ID = :userbd
    AND RU.ROLU_ROLE_ID = SEGU.SEG_ROLE_ID
    AND SEGU.SEG_MENT_ID = MENT.MENT_ID
    --AND SEGU.SEG_MENT_ID = MEND.MENT_ID
    AND SEGU.SEG_MEND_ID = MEND.MEND_ID
    AND MENT.MENT_ID=MEND.MENT_ID
   AND SYS_ID=1
   ORDER BY MEND_PADRE DESC
