SELECT
	A.CODEMP,
	A.NOMBRE,
	A.APELLIDO,
	A.NOMBRE || ' ' || A.APELLIDO "fullName",
	A.PUESTO,
	REPLACE (A.DPI, ' ', '') DPI,
	A.CORREOCOMBEX,
	A.DEPTO,
	A.GERENTE,
	B.COD_USUARIO,
	:empresa empresa
FROM
	CB1.VM_EMPLEADOS_COMBEX A
	LEFT OUTER JOIN SAB.SAB_GENE_USERS B ON A.CODEMP = B.CODEMP
WHERE
	COD_USUARIO = UPPER(:userbd)
	